version: '3'
services:
  localdb:
      image: mysql:latest
      #restart: always
      volumes: 
       - ./db/data:/var/lib/mysql
       - ./db/scripts:/mysqlscripts
      #ports:
       #- hostport:clientport
      #depends_on:
       #- service-name-here
      environment: 
        MYSQL_ROOT_PASSWORD: test123!
  localredis: 
      image: redis:latest
      ports: 
        - 6379:6379
  dotnetapp:
      image: microsoft/aspnetcore-build
      #restart:always
      depends_on: 
        - localdb
        - localredis
      volumes:
        - ./dotnetApps/app2:/app
      ports:
        - 8888:5000
      working_dir: /app
      command: 
        dotnet /app/app2.dll --urls=http://*:5000
  nginxserver:
      image: nginx:latest
      depends_on:
       - dotnetapp
      ports: 
       - 443:443
       - 80:80
      volumes:
       - ./nginx-server:/ngxhost
       - /etc/letsencrypt:/etc/letsencrypt
      command:
       [nginx,'-p','/ngxhost','-c', 'nginx.conf','-g','daemon off;'] 
      
      

  